name: wine_prefix_manager
description: A tool to manage Wine and Proton prefixes
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Cross-platform and Linux dependencies only
  shared_preferences: ^2.2.1
  provider: ^6.0.0
  path: ^1.8.0
  http: ^1.1.0  # For API requests to GitHub
  dio: ^5.0.0
  process_run: ^0.13.0
  file_picker: ^5.0.0
  url_launcher: ^6.1.6
  window_manager: ^0.3.7
  connectivity_plus: ^5.0.0 # For checking network status
  archive: ^3.3.7  # For tar.gz extraction
  # Use a specific version of bitsdojo_window with Linux fixes
  bitsdojo_window: ^0.1.5
  intl: ^0.18.1
  share_plus: ^7.0.2
  file_saver: ^0.2.4
  # Add flutter_acrylic for better transparency support
  flutter_acrylic: ^1.1.3
  # ...any other dependencies you need...

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
